ui: mocha-bdd
server: ./test/support/server.js
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 6..latest
